import { MigrationInterface, QueryRunner } from "typeorm";

export class addedUserEntity1753382749426 implements MigrationInterface {
    name = 'addedUserEntity1753382749426'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "lead_sources" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted" boolean DEFAULT false, "deleted_at" TIMESTAMP, "name" character varying NOT NULL, CONSTRAINT "UQ_330b3b33744bda1d17d3053a49c" UNIQUE ("name"), CONSTRAINT "PK_bc885a4409ec70ee5a810dbbd6f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "lead_attachments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted" boolean DEFAULT false, "deleted_at" TIMESTAMP, "file_path" character varying, "file_type" character varying, "file_name" character varying, "lead_id" uuid NOT NULL, "uploaded_by" uuid, CONSTRAINT "PK_0b6dfe5cf4c3ddca625100789d8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."projects_status_enum" AS ENUM('Open', 'In Progress', 'Final', 'Completed', 'Cancelled', 'On Hold')`);
        await queryRunner.query(`CREATE TABLE "projects" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted" boolean DEFAULT false, "deleted_at" TIMESTAMP, "name" character varying(255), "leadName" character varying(255), "renewalDate" TIMESTAMP, "status" "public"."projects_status_enum" NOT NULL DEFAULT 'Open', CONSTRAINT "PK_6271df0a7aed1d6c0691ce6ac50" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."tasks_priority_enum" AS ENUM('High', 'Medium', 'Low')`);
        await queryRunner.query(`CREATE TYPE "public"."tasks_status_enum" AS ENUM('Open', 'In Progress', 'Final', 'Completed', 'Cancelled', 'On Hold')`);
        await queryRunner.query(`CREATE TABLE "tasks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted" boolean DEFAULT false, "deleted_at" TIMESTAMP, "taskName" character varying(255) NOT NULL, "priority" "public"."tasks_priority_enum" NOT NULL DEFAULT 'Medium', "endDate" TIMESTAMP, "status" "public"."tasks_status_enum" NOT NULL DEFAULT 'Open', "description" text, "assigned_to_id" uuid, "project_id" uuid, CONSTRAINT "PK_8d12ff38fcc62aaba2cab748772" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted" boolean DEFAULT false, "deleted_at" TIMESTAMP, "role" text, "permissions" text array NOT NULL, CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "project_tasks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted" boolean DEFAULT false, "deleted_at" TIMESTAMP, "title" character varying(150) NOT NULL, "description" text, "due_date" date, "status" character varying(50) NOT NULL DEFAULT 'Pending', "assigned_to" character varying(100), "milestone_id" uuid, CONSTRAINT "PK_b1b6204912a6f44133df3a4518b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "project_milestones" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted" boolean DEFAULT false, "deleted_at" TIMESTAMP, "name" character varying(100) NOT NULL, "description" text, "start_date" TIMESTAMP, "end_date" TIMESTAMP, "actual_date" TIMESTAMP, "estimated_date" TIMESTAMP, "assigned_to" character varying(100), "status" character varying(50) NOT NULL, "remark" text, "project_id" uuid, CONSTRAINT "PK_0c561300a12c6ba3ad793dff4b8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "project_task_master" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted" boolean DEFAULT false, "deleted_at" TIMESTAMP, "title" character varying(150) NOT NULL, "description" text, "estimated_days" integer, "milestone_master_id" uuid, CONSTRAINT "PK_9be01e907aa70ecc978697c5d44" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "project_milestone_master" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted" boolean DEFAULT false, "deleted_at" TIMESTAMP, "name" character varying(100) NOT NULL, "description" text, "estimated_days" integer, "template_id" uuid, CONSTRAINT "PK_fa0b94259b31a2e75754580473b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "project_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted" boolean DEFAULT false, "deleted_at" TIMESTAMP, "name" text NOT NULL, "description" text, "project_type" text, "estimated_days" integer, CONSTRAINT "PK_8ad4477f22e9b6e0880f1053449" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "lead_types" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted" boolean DEFAULT false, "deleted_at" TIMESTAMP, "name" character varying NOT NULL, CONSTRAINT "UQ_134761eff852159ee3e7ae4fd58" UNIQUE ("name"), CONSTRAINT "PK_f27660eb2435352c35da1c7f87c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."Project _status_enum" AS ENUM('Open', 'In Progress', 'Completed', 'Cancelled', 'On Hold')`);
        await queryRunner.query(`CREATE TYPE "public"."Project _renewal_type_enum" AS ENUM('NONE', 'MONTHLY', 'QUARTERLY', 'YEARLY', 'CUSTOM')`);
        await queryRunner.query(`CREATE TABLE "Project " ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted" boolean DEFAULT false, "deleted_at" TIMESTAMP, "name" character varying(150) NOT NULL, "description" text, "status" "public"."Project _status_enum" NOT NULL DEFAULT 'Open', "budget" numeric(12,2), "estimated_cost" numeric(12,2), "actual_cost" numeric(12,2), "cost_of_labour" numeric(12,2), "overhead_cost" numeric(12,2), "extra_cost" numeric(12,2), "start_date" TIMESTAMP, "end_date" TIMESTAMP, "actual_start_date" TIMESTAMP, "actual_end_date" TIMESTAMP, "renewal_type" "public"."Project _renewal_type_enum", "renewal_date" TIMESTAMP, "is_renewal" boolean NOT NULL DEFAULT false, "client_id" uuid, "project_type" uuid, "template_id" uuid, CONSTRAINT "PK_29ac2110d327bb1055e1d1d945e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "project_attachments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted" boolean DEFAULT false, "deleted_at" TIMESTAMP, "file_path" character varying, "file_type" character varying, "file_name" character varying, "project_id" uuid NOT NULL, "uploaded_by" uuid, CONSTRAINT "PK_e0adaaabd364382782d8ef14fcc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "eilog_types" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted" boolean DEFAULT false, "deleted_at" TIMESTAMP, "name" text, CONSTRAINT "UQ_612956ad5f912cb9cdb365f58b2" UNIQUE ("name"), CONSTRAINT "PK_9d5a1b0381370ae54eefa0480d3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "eilog_heads" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted" boolean DEFAULT false, "deleted_at" TIMESTAMP, "name" text, CONSTRAINT "UQ_d25b46a7dac083820cc65723fe6" UNIQUE ("name"), CONSTRAINT "PK_2f72f9942d07bdb36e949e25197" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."eilogs_paymentmode_enum" AS ENUM('Cash', 'Online', 'UPI', 'Bank Transfer', 'Cheque', 'Others')`);
        await queryRunner.query(`CREATE TABLE "eilogs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted" boolean DEFAULT false, "deleted_at" TIMESTAMP, "description" text, "income" numeric(15,2), "expense" numeric(15,2), "paymentMode" "public"."eilogs_paymentmode_enum" NOT NULL, "attachment" text, "eilog_type_id" uuid, "eilog_head_id" uuid, "created_by" uuid, CONSTRAINT "PK_20d659c68b8e2968ceaee8542f9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted" boolean DEFAULT false, "deleted_at" TIMESTAMP, "email" character varying, "first_name" character varying, "last_name" character varying, "phone_number" character varying, "dob" TIMESTAMP, "otp" character varying(6), "otpExpiresAt" TIMESTAMP, "isOtpVerified" boolean NOT NULL DEFAULT false, "password" character varying NOT NULL, "role_id" uuid, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "lead_status_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted" boolean DEFAULT false, "deleted_at" TIMESTAMP, "status_remarks" text, "lead_id" uuid NOT NULL, "status_id" uuid, "changed_by" uuid, CONSTRAINT "PK_77ab85c988b965db46f0f52ffe2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "lead_statuses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted" boolean DEFAULT false, "deleted_at" TIMESTAMP, "name" character varying NOT NULL, "color" character varying, CONSTRAINT "UQ_41e02f3e4a13ac95c6f02508fda" UNIQUE ("name"), CONSTRAINT "PK_8f52fd712b486354477d9df1e57" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."lead_followups_status_enum" AS ENUM('RESCHEDULE', 'PENDING', 'AWAITING RESPONSE', 'NO RESPONSE', 'FAILED', 'COMPLETED')`);
        await queryRunner.query(`CREATE TABLE "lead_followups" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted" boolean DEFAULT false, "deleted_at" TIMESTAMP, "status" "public"."lead_followups_status_enum" NOT NULL DEFAULT 'PENDING', "due_date" TIMESTAMP, "completed_date" TIMESTAMP, "remarks" text, "lead_id" uuid, "user_id" uuid, CONSTRAINT "PK_676d6790527ecab481091776cd2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "leads" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted" boolean DEFAULT false, "deleted_at" TIMESTAMP, "first_name" character varying, "last_name" character varying, "created_by" character varying, "updated_by" character varying, "company" character varying, "phone" character varying, "escalate_to" boolean DEFAULT false, "other_contact" character varying, "email" text array, "location" character varying, "budget" numeric, "requirement" text, "possibility_of_conversion" numeric(5,2), "source_id" uuid, "type_id" uuid, "status_id" uuid, "assigned_to" uuid, CONSTRAINT "PK_cd102ed7a9a4ca7d4d8bfeba406" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "clients" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted" boolean DEFAULT false, "deleted_at" TIMESTAMP, "name" character varying(100) NOT NULL, "email" character varying(100), "contact_number" character varying(20) NOT NULL, "address" text, "website" text, "company_name" character varying(150), "contact_person" character varying(100), "gst_number" character varying(20), "lead_id" uuid, CONSTRAINT "PK_f1ab7cf3a5714dbc6bb4e1c28a4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "client_details" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted" boolean DEFAULT false, "deleted_at" TIMESTAMP, "client_contact" character varying(100) NOT NULL, "contact_person" character varying(100), "email" character varying(100), "other_contact" character varying(20), "designation" character varying(100), "client_id" uuid NOT NULL, CONSTRAINT "PK_65926657762853a6281b7d9b9f0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."client_followups_status_enum" AS ENUM('RESCHEDULE', 'PENDING', 'AWAITING RESPONSE', 'NO RESPONSE', 'FAILED', 'COMPLETED')`);
        await queryRunner.query(`CREATE TABLE "client_followups" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted" boolean DEFAULT false, "deleted_at" TIMESTAMP, "status" "public"."client_followups_status_enum" NOT NULL DEFAULT 'PENDING', "due_date" TIMESTAMP, "completed_date" TIMESTAMP, "remarks" text, "client_id" uuid, "user_id" uuid, "project_task_id" uuid, CONSTRAINT "PK_493cbd6d4437d569e07448e5854" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "daily_task_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted" boolean DEFAULT false, "deleted_at" TIMESTAMP, "task_title" character varying(150) NOT NULL, "assigned_to" character varying(150), "description" text, "entry_date" date NOT NULL, "hours_spent" numeric(5,2), "status" character varying(50) NOT NULL DEFAULT 'Pending', "priority" character varying(20) NOT NULL DEFAULT 'Medium', "remarks" text, "project_id" uuid NOT NULL, CONSTRAINT "PK_2d1d90232fbc41387daeece1609" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('TASK_ASSIGNED', 'TASK_UPDATED', 'TASK_COMPLETED', 'LEAD_ASSIGNED', 'LEAD_UPDATED', 'LEAD_STATUS_CHANGED', 'FOLLOWUP_CREATED', 'FOLLOWUP_UPDATED', 'FOLLOWUP_REMINDER', 'QUOTATION_SENT', 'BUSINESS_DONE', 'LEAD_ESCALATED')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted" boolean DEFAULT false, "deleted_at" TIMESTAMP, "type" "public"."notifications_type_enum" NOT NULL, "message" character varying NOT NULL, "isRead" boolean NOT NULL DEFAULT false, "metadata" jsonb, "userId" character varying NOT NULL, "user_id" uuid, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted" boolean DEFAULT false, "deleted_at" TIMESTAMP, "userId" character varying NOT NULL, "isExpired" boolean NOT NULL DEFAULT false, "ipAddress" character varying NOT NULL, "userAgent" character varying NOT NULL, CONSTRAINT "PK_3238ef96f18b355b671619111bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "task_comments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted" boolean DEFAULT false, "deleted_at" TIMESTAMP, "remarks" text NOT NULL, "task_id" uuid NOT NULL, "assigned_to" uuid NOT NULL, CONSTRAINT "PK_83b99b0b03db29d4cafcb579b77" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "lead_attachments" ADD CONSTRAINT "FK_9294774726472d04ec4d527102e" FOREIGN KEY ("lead_id") REFERENCES "leads"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lead_attachments" ADD CONSTRAINT "FK_06cf96fc063c960fe459944b9d8" FOREIGN KEY ("uploaded_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_9430f12c5a1604833f64595a57f" FOREIGN KEY ("assigned_to_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_9eecdb5b1ed8c7c2a1b392c28d4" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_tasks" ADD CONSTRAINT "FK_f0cc6c0ff02c1d9ea489166df86" FOREIGN KEY ("milestone_id") REFERENCES "project_milestones"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_milestones" ADD CONSTRAINT "FK_4072d2ff8e9ee23e9e03e5f6721" FOREIGN KEY ("project_id") REFERENCES "Project "("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_task_master" ADD CONSTRAINT "FK_c2e719c193b00bf90e283075272" FOREIGN KEY ("milestone_master_id") REFERENCES "project_milestone_master"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_milestone_master" ADD CONSTRAINT "FK_76aa1d8984d1dc045ca856f5dc3" FOREIGN KEY ("template_id") REFERENCES "project_templates"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Project " ADD CONSTRAINT "FK_9225460e0ae5bf849f284966c36" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Project " ADD CONSTRAINT "FK_467f28fe2224a2c1488c7d17f38" FOREIGN KEY ("project_type") REFERENCES "lead_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Project " ADD CONSTRAINT "FK_4956049bd6494d81cbb493ff455" FOREIGN KEY ("template_id") REFERENCES "project_templates"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_attachments" ADD CONSTRAINT "FK_7c02c61e27153a78244411756a2" FOREIGN KEY ("project_id") REFERENCES "Project "("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_attachments" ADD CONSTRAINT "FK_26b600ea32a6dad9da303112aa3" FOREIGN KEY ("uploaded_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "eilogs" ADD CONSTRAINT "FK_62a550e97231eff87081c351ff3" FOREIGN KEY ("eilog_type_id") REFERENCES "eilog_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "eilogs" ADD CONSTRAINT "FK_504469f35c79cd73a1645207a7b" FOREIGN KEY ("eilog_head_id") REFERENCES "eilog_heads"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "eilogs" ADD CONSTRAINT "FK_32dec867690b9c5c3f8776cd51f" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lead_status_history" ADD CONSTRAINT "FK_c4522d183d638dcfcdd68868eea" FOREIGN KEY ("lead_id") REFERENCES "leads"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lead_status_history" ADD CONSTRAINT "FK_4cff1bc2eac5ebc708fe955ae5b" FOREIGN KEY ("status_id") REFERENCES "lead_statuses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lead_status_history" ADD CONSTRAINT "FK_54fd16ff875ab6c6f48bf2e2c5a" FOREIGN KEY ("changed_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lead_followups" ADD CONSTRAINT "FK_4bbc75b036d3ec7a19ba594ea9f" FOREIGN KEY ("lead_id") REFERENCES "leads"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lead_followups" ADD CONSTRAINT "FK_72332822f7f1f3e81b3a2919cd8" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leads" ADD CONSTRAINT "FK_3841680163f11774ec3dbff1941" FOREIGN KEY ("source_id") REFERENCES "lead_sources"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leads" ADD CONSTRAINT "FK_6e28c8e9b340c0f5dcbf8415b6a" FOREIGN KEY ("type_id") REFERENCES "lead_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leads" ADD CONSTRAINT "FK_a2c42b471f34d261cfbad2427d6" FOREIGN KEY ("status_id") REFERENCES "lead_statuses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leads" ADD CONSTRAINT "FK_5c37aa54e3b06f6733d56007e0c" FOREIGN KEY ("assigned_to") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "FK_0d6be4fdc136070fefe2154b03e" FOREIGN KEY ("lead_id") REFERENCES "leads"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "client_details" ADD CONSTRAINT "FK_0be14bbd3b8d2582604b4e41222" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "client_followups" ADD CONSTRAINT "FK_d16b24511aa0885871a88970bf4" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "client_followups" ADD CONSTRAINT "FK_a514e7f0cbb10d41e4af5235d42" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "client_followups" ADD CONSTRAINT "FK_01d83f1697ba365eccf11e2373b" FOREIGN KEY ("project_task_id") REFERENCES "project_tasks"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "daily_task_entries" ADD CONSTRAINT "FK_554ede8c5e95b8a47c3d9d9c995" FOREIGN KEY ("project_id") REFERENCES "Project "("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_comments" ADD CONSTRAINT "FK_ba9e465cfc707006e60aae59946" FOREIGN KEY ("task_id") REFERENCES "project_tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_comments" ADD CONSTRAINT "FK_c56dff50f457ef3fd7fce14a12c" FOREIGN KEY ("assigned_to") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "task_comments" DROP CONSTRAINT "FK_c56dff50f457ef3fd7fce14a12c"`);
        await queryRunner.query(`ALTER TABLE "task_comments" DROP CONSTRAINT "FK_ba9e465cfc707006e60aae59946"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "daily_task_entries" DROP CONSTRAINT "FK_554ede8c5e95b8a47c3d9d9c995"`);
        await queryRunner.query(`ALTER TABLE "client_followups" DROP CONSTRAINT "FK_01d83f1697ba365eccf11e2373b"`);
        await queryRunner.query(`ALTER TABLE "client_followups" DROP CONSTRAINT "FK_a514e7f0cbb10d41e4af5235d42"`);
        await queryRunner.query(`ALTER TABLE "client_followups" DROP CONSTRAINT "FK_d16b24511aa0885871a88970bf4"`);
        await queryRunner.query(`ALTER TABLE "client_details" DROP CONSTRAINT "FK_0be14bbd3b8d2582604b4e41222"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "FK_0d6be4fdc136070fefe2154b03e"`);
        await queryRunner.query(`ALTER TABLE "leads" DROP CONSTRAINT "FK_5c37aa54e3b06f6733d56007e0c"`);
        await queryRunner.query(`ALTER TABLE "leads" DROP CONSTRAINT "FK_a2c42b471f34d261cfbad2427d6"`);
        await queryRunner.query(`ALTER TABLE "leads" DROP CONSTRAINT "FK_6e28c8e9b340c0f5dcbf8415b6a"`);
        await queryRunner.query(`ALTER TABLE "leads" DROP CONSTRAINT "FK_3841680163f11774ec3dbff1941"`);
        await queryRunner.query(`ALTER TABLE "lead_followups" DROP CONSTRAINT "FK_72332822f7f1f3e81b3a2919cd8"`);
        await queryRunner.query(`ALTER TABLE "lead_followups" DROP CONSTRAINT "FK_4bbc75b036d3ec7a19ba594ea9f"`);
        await queryRunner.query(`ALTER TABLE "lead_status_history" DROP CONSTRAINT "FK_54fd16ff875ab6c6f48bf2e2c5a"`);
        await queryRunner.query(`ALTER TABLE "lead_status_history" DROP CONSTRAINT "FK_4cff1bc2eac5ebc708fe955ae5b"`);
        await queryRunner.query(`ALTER TABLE "lead_status_history" DROP CONSTRAINT "FK_c4522d183d638dcfcdd68868eea"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`ALTER TABLE "eilogs" DROP CONSTRAINT "FK_32dec867690b9c5c3f8776cd51f"`);
        await queryRunner.query(`ALTER TABLE "eilogs" DROP CONSTRAINT "FK_504469f35c79cd73a1645207a7b"`);
        await queryRunner.query(`ALTER TABLE "eilogs" DROP CONSTRAINT "FK_62a550e97231eff87081c351ff3"`);
        await queryRunner.query(`ALTER TABLE "project_attachments" DROP CONSTRAINT "FK_26b600ea32a6dad9da303112aa3"`);
        await queryRunner.query(`ALTER TABLE "project_attachments" DROP CONSTRAINT "FK_7c02c61e27153a78244411756a2"`);
        await queryRunner.query(`ALTER TABLE "Project " DROP CONSTRAINT "FK_4956049bd6494d81cbb493ff455"`);
        await queryRunner.query(`ALTER TABLE "Project " DROP CONSTRAINT "FK_467f28fe2224a2c1488c7d17f38"`);
        await queryRunner.query(`ALTER TABLE "Project " DROP CONSTRAINT "FK_9225460e0ae5bf849f284966c36"`);
        await queryRunner.query(`ALTER TABLE "project_milestone_master" DROP CONSTRAINT "FK_76aa1d8984d1dc045ca856f5dc3"`);
        await queryRunner.query(`ALTER TABLE "project_task_master" DROP CONSTRAINT "FK_c2e719c193b00bf90e283075272"`);
        await queryRunner.query(`ALTER TABLE "project_milestones" DROP CONSTRAINT "FK_4072d2ff8e9ee23e9e03e5f6721"`);
        await queryRunner.query(`ALTER TABLE "project_tasks" DROP CONSTRAINT "FK_f0cc6c0ff02c1d9ea489166df86"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_9eecdb5b1ed8c7c2a1b392c28d4"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_9430f12c5a1604833f64595a57f"`);
        await queryRunner.query(`ALTER TABLE "lead_attachments" DROP CONSTRAINT "FK_06cf96fc063c960fe459944b9d8"`);
        await queryRunner.query(`ALTER TABLE "lead_attachments" DROP CONSTRAINT "FK_9294774726472d04ec4d527102e"`);
        await queryRunner.query(`DROP TABLE "task_comments"`);
        await queryRunner.query(`DROP TABLE "sessions"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP TABLE "daily_task_entries"`);
        await queryRunner.query(`DROP TABLE "client_followups"`);
        await queryRunner.query(`DROP TYPE "public"."client_followups_status_enum"`);
        await queryRunner.query(`DROP TABLE "client_details"`);
        await queryRunner.query(`DROP TABLE "clients"`);
        await queryRunner.query(`DROP TABLE "leads"`);
        await queryRunner.query(`DROP TABLE "lead_followups"`);
        await queryRunner.query(`DROP TYPE "public"."lead_followups_status_enum"`);
        await queryRunner.query(`DROP TABLE "lead_statuses"`);
        await queryRunner.query(`DROP TABLE "lead_status_history"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "eilogs"`);
        await queryRunner.query(`DROP TYPE "public"."eilogs_paymentmode_enum"`);
        await queryRunner.query(`DROP TABLE "eilog_heads"`);
        await queryRunner.query(`DROP TABLE "eilog_types"`);
        await queryRunner.query(`DROP TABLE "project_attachments"`);
        await queryRunner.query(`DROP TABLE "Project "`);
        await queryRunner.query(`DROP TYPE "public"."Project _renewal_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."Project _status_enum"`);
        await queryRunner.query(`DROP TABLE "lead_types"`);
        await queryRunner.query(`DROP TABLE "project_templates"`);
        await queryRunner.query(`DROP TABLE "project_milestone_master"`);
        await queryRunner.query(`DROP TABLE "project_task_master"`);
        await queryRunner.query(`DROP TABLE "project_milestones"`);
        await queryRunner.query(`DROP TABLE "project_tasks"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "tasks"`);
        await queryRunner.query(`DROP TYPE "public"."tasks_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tasks_priority_enum"`);
        await queryRunner.query(`DROP TABLE "projects"`);
        await queryRunner.query(`DROP TYPE "public"."projects_status_enum"`);
        await queryRunner.query(`DROP TABLE "lead_attachments"`);
        await queryRunner.query(`DROP TABLE "lead_sources"`);
    }

}
